import { Course } from "@/types/courses/course"


export const courses:Course[] = [
    {
      ID: 134,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Revalidation Training Course for Masters and Deck Officers  (RUT-DECK)',
      Image: '../ServerUpload/Courses/ProfilePicture/134.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: ['BSID\nPASSPORT\nCDC\nCoC\nINDoS'],
      DurationofCourse: ['3 Days'],
      Eligibilty: ['ALL MASTERS & DECK OFFICERS'],
      CourseScheduleandFee: '8500',
      CoursePDF: '../ServerUpload/Courses/PDF/134.pdf',
      Code: 'RUT-DECK',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 47,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Refresher and Updating Training Course for all Engineers (RUT-ENGINE)',
      Image: '../ServerUpload/Courses/ProfilePicture/47.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: ['Passport ', '\nCDC ', '\nINDoS ', '\nCOC\n&  BSID'],
      DurationofCourse: ['4 Days'],
      Eligibilty: [
        'This course is applicable to all those Engineer Officers (Operational level and Management Level) whose CoC have already been issued in compliance with STCW 2010 amendments and aspiring to revalidate their CoC.',
      ],
      CourseScheduleandFee: '6300',
      CoursePDF: '../ServerUpload/Courses/PDF/47.pdf',
      Code: 'RUTC (E.O)',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 133,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'General Operator`s Certificate for GMDSS',
      Image: '../ServerUpload/Courses/ProfilePicture/133.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        '10th Certificate & Mark sheet\n12th Certificate & Mark sheet\nPassport\nCDC sea time pages \nIndos Profile\n& BSID',
      ],
      DurationofCourse: ['12 Days'],
      Eligibilty: [
        '10th Certificate & Mark sheet\n12th Certificate & Mark sheet\nPassport\nCDC sea time pages\nBSID',
      ],
      CourseScheduleandFee: '25000',
      CoursePDF: '../ServerUpload/Courses/PDF/133.pdf',
      Code: 'GMDSS',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 12,
      CourseScheduleDetails: [
        {
          ID: 20738,
          CourseID: 133,
          CourseDate: '05/Sep/2024',
          CourseEndDate: '20/Sep/2024',
          CourseFee: '25000',
          SeatAvaiable: 12,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20739,
          CourseID: 133,
          CourseDate: '03/Oct/2024',
          CourseEndDate: '19/Oct/2024',
          CourseFee: '25000',
          SeatAvaiable: 12,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20740,
          CourseID: 133,
          CourseDate: '01/Nov/2024',
          CourseEndDate: '14/Nov/2024',
          CourseFee: '25000',
          SeatAvaiable: 12,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20741,
          CourseID: 133,
          CourseDate: '02/Dec/2024',
          CourseEndDate: '13/Dec/2024',
          CourseFee: '25000',
          SeatAvaiable: 12,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
      ],
    },
    {
      ID: 136,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Restricted Operators Certificate (GMDSS-ROC)',
      Image:
        '../ServerUpload/Temp/2024/January/d378c846-a2e1-4b4a-aef7-145acc912a35.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: ['PASSPORT\nINDoS'],
      DurationofCourse: ['5 Days'],
      Eligibilty: ['Class X  certificate\nOr\nValid COC or COP'],
      CourseScheduleandFee: '0',
      CoursePDF: null,
      Code: 'GMDSS-ROC',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 12,
      CourseScheduleDetails: [],
    },
    {
      ID: 1,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Medical Care',
      Image: '../ServerUpload/Courses/ProfilePicture/1.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC No. ',
        '\nINDoS No. ',
        '\nLAST MFA (Medical First Aid Certificate)\n&  BSID',
      ],
      DurationofCourse: ['10 Days'],
      Eligibilty: ['COC As 2nd Mate (FG)'],
      CourseScheduleandFee: '6300',
      CoursePDF: '../ServerUpload/Courses/PDF/1.pdf',
      Code: 'MC',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 10,
      CourseScheduleDetails: [],
    },
    {
      ID: 8,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'ADVANCED TRAINING FOR OIL TANKER CARGO OPERATIONS (TASCO)',
      Image: '../ServerUpload/Courses/ProfilePicture/8.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC ',
        '\nINDoS ',
        '\nCOC / Watchkeeping / COP / Cookery Certificate\n&  BSID',
      ],
      DurationofCourse: ['10 Days'],
      Eligibilty: [
        '(1) COC As 2nd Mate (FG) / MEO IV/ NWKO (NCV) ',
        '\n(2) AFFC Certificate. ',
        '\n(3) At Least 3 Months Sea Going Service On Respective Tankers.\nOR\nRespective Tanker Familiarisation Course Certificate.',
      ],
      CourseScheduleandFee: '6300',
      CoursePDF: '../ServerUpload/Courses/PDF/8.pdf',
      Code: 'TASCO',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 7,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'ADVANCED TRAINING FOR CHEMICAL TANKER CARGO OPERATIONS (CHEMCO)',
      Image: '../ServerUpload/Courses/ProfilePicture/7.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC ',
        '\nINDoS ',
        '\nCOC / Watchkeeping / COP / Cookery Certificate\n&  BSID',
      ],
      DurationofCourse: ['10 Days'],
      Eligibilty: [
        '(1) COC As 2nd Mate (FG) / MEO IV/ NWKO (NCV) ',
        '\n(2) AFFC Certificate ',
        '\n(3) At Least 3 Months Sea Going Service On Respective Tankers\nOR\nRespective Tanker Familiarisation Course Certificate',
      ],
      CourseScheduleandFee: '8300',
      CoursePDF: '../ServerUpload/Courses/PDF/7.pdf',
      Code: 'CHEMCO',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 70,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Proficiency In Survival Craft and Rescue Boats (PSCRB)',
      Image: '../ServerUpload/Courses/ProfilePicture/70.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC ',
        '\nINDOS ',
        '\nBSID',
        '\nPST CERTIFICATE ',
        '\nTWO PHOTOGRAPHS (30 X 25MM)\n&  BSID',
      ],
      DurationofCourse: ['05 Days'],
      Eligibilty: [
        'VALID MEDICAL FITNESS CERTIFICATE IN SPECIFIED FORMAT APPROVED BY DGS ',
        ' PPROVED PRE-SEA TRAINING COURSE AND 6 MONTHS SEA SERVICE\n- OR - OFFICERS CADETS AND RATING HAVING 12 MONTHS SEA SERVICE\n**MEDICAL MASTER CHECKER PRINTOUT WITH VALID',
      ],
      CourseScheduleandFee: '6300',
      CoursePDF: '../ServerUpload/Courses/PDF/70.pdf',
      Code: 'PSCRB',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 73,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'ADVANCED FIRE FIGHTING (AFF)',
      Image: '../ServerUpload/Courses/ProfilePicture/73.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC ',
        '\nINDOS ',
        '\nFPFF CERTIFICATE ',
        '\nDG APPROVED VALID MEDICAL FITNESS CERTIFICATE ',
        '\nTWO COLOR PHOTOGRAPHS (30 X 25MM) ',
        '\nBOILER SUIT & SAFETY SHOES\n&  BSID',
      ],
      DurationofCourse: ['05 Days'],
      Eligibilty: [
        'VALID MEDICAL FITNESS CERTIFICATE  IN SPECIFIED FORMAT APPROVED BY DGS ',
        '\nSEA TIME ATLEAST 6 MONTHS\n**MEDICAL MASTER CHECKER PRINTOUT WITH VALID',
      ],
      CourseScheduleandFee: '5300',
      CoursePDF: '../ServerUpload/Courses/PDF/73.pdf',
      Code: 'AFF',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 54,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'MEDICAL FIRST AID (MFA)',
      Image: '../ServerUpload/Courses/ProfilePicture/54.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC ',
        '\nCOC/COP ',
        '\nINDOS\n&  BSID',
      ],
      DurationofCourse: ['04 Days'],
      Eligibilty: [
        'AN APPROVED SEA GOING SERVICES FOR SIX MONTHS ',
        '\n COPY OF EFA,PST, FPFF',
      ],
      CourseScheduleandFee: '3300',
      CoursePDF: '../ServerUpload/Courses/PDF/54.pdf',
      Code: 'MFA',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 12,
      CourseScheduleDetails: [],
    },
    {
      ID: 68,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'ADVANCED SHIPBOARD MANAGEMENT (ASM)',
      Image: '../ServerUpload/Courses/ProfilePicture/68.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC ',
        '\nINDOS ',
        '\nCOS AS FIRTST MATE(FG)\n&  BSID',
      ],
      DurationofCourse: ['45 Days'],
      Eligibilty: [
        'Should have Sea Service of 12 Months after obtaining 1st Mate (FG) COC /36 Months Sea Service after obtaining 2nd Mate (FG) COC OR\n30 Months Sea Service required if sailed as a Chief Officer for 12 months after obtaining First Mate(FG) COC.',
      ],
      CourseScheduleandFee: '20000',
      CoursePDF: '../ServerUpload/Courses/PDF/68.pdf',
      Code: 'ASM',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: false,
      TotalSeats: 20,
      CourseScheduleDetails: [],
    },
    {
      ID: 11,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'FIRST MATE  (FG) PHASE - I',
      Image: '../ServerUpload/Courses/ProfilePicture/11.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC ',
        '\nCOC / COP ',
        ' \nINDoS .\n&  BSID',
      ],
      DurationofCourse: ['03 Months'],
      Eligibilty: ['9 Months Sea Service after obtaining 2nd Mate (FG) COC'],
      CourseScheduleandFee: '20000',
      CoursePDF: '../ServerUpload/Courses/PDF/11.pdf',
      Code: 'PHASE I',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 40,
      CourseScheduleDetails: [
        {
          ID: 20265,
          CourseID: 11,
          CourseDate: '15/Aug/2024',
          CourseEndDate: '14/Nov/2024',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20266,
          CourseID: 11,
          CourseDate: '15/Sep/2024',
          CourseEndDate: '14/Dec/2024',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20267,
          CourseID: 11,
          CourseDate: '15/Oct/2024',
          CourseEndDate: '14/Jan/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20268,
          CourseID: 11,
          CourseDate: '15/Nov/2024',
          CourseEndDate: '14/Feb/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20269,
          CourseID: 11,
          CourseDate: '15/Dec/2024',
          CourseEndDate: '14/Mar/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
      ],
    },
    {
      ID: 12,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'FIRST MATE (FG) PHASE - II',
      Image: '../ServerUpload/Courses/ProfilePicture/12.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC ',
        '\nCOC \nINDoS .\nPhase-I cert\n&  BSID',
      ],
      DurationofCourse: ['03 Months'],
      Eligibilty: [
        '(A)18 Months Sea Service after obtaining 2nd Mate (FG) COC ',
        '\n(B) Phase I (FG) Attendance Certificate',
      ],
      CourseScheduleandFee: '20000',
      CoursePDF: '../ServerUpload/Courses/PDF/12.pdf',
      Code: 'PHASE II',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 40,
      CourseScheduleDetails: [
        {
          ID: 20277,
          CourseID: 12,
          CourseDate: '15/Aug/2024',
          CourseEndDate: '14/Nov/2024',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20278,
          CourseID: 12,
          CourseDate: '15/Sep/2024',
          CourseEndDate: '14/Dec/2024',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20279,
          CourseID: 12,
          CourseDate: '15/Oct/2024',
          CourseEndDate: '14/Jan/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20280,
          CourseID: 12,
          CourseDate: '15/Nov/2024',
          CourseEndDate: '14/Feb/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20281,
          CourseID: 12,
          CourseDate: '15/Dec/2024',
          CourseEndDate: '14/Mar/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
      ],
    },
    {
      ID: 13,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'SECOND MATE (F.G.)',
      Image: '../ServerUpload/Courses/ProfilePicture/13.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC ',
        '\nCOC / COP ',
        ' \nINDoS.\n&  BSID',
      ],
      DurationofCourse: ['04 Months'],
      Eligibilty: ['18 MONTHS SEA SERVICE CERTIFICATE'],
      CourseScheduleandFee: '20000',
      CoursePDF: '../ServerUpload/Courses/PDF/13.pdf',
      Code: 'SECOND MATE',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 40,
      CourseScheduleDetails: [
        {
          ID: 20289,
          CourseID: 13,
          CourseDate: '15/Aug/2024',
          CourseEndDate: '14/Dec/2024',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20290,
          CourseID: 13,
          CourseDate: '15/Sep/2024',
          CourseEndDate: '14/Jan/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20291,
          CourseID: 13,
          CourseDate: '15/Oct/2024',
          CourseEndDate: '14/Feb/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20292,
          CourseID: 13,
          CourseDate: '15/Nov/2024',
          CourseEndDate: '14/Mar/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20293,
          CourseID: 13,
          CourseDate: '15/Dec/2024',
          CourseEndDate: '14/Apr/2025',
          CourseFee: '20000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
      ],
    },
    {
      ID: 96,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'MEO Class -1 Preparatory Course (2 Months)',
      Image: '../ServerUpload/Courses/ProfilePicture/96.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'CoC as MEO Class II + 18 Months Sea service (12 Months as 2nd Engineer Officer) including 365 days propelling time. (or) - CoC as MEO Class II + 24 Months Sea service including 485 days propelling time. , INDOS Number is Mandatory + CDC WITH STAMP PAGES, PASSPORT , MEO-II CERT..\n& BSID',
      ],
      DurationofCourse: ['60 Day'],
      Eligibilty: [
        'CoC as MEO Class II + 18 Months Sea service (12 Months as 2nd Engineer Officer) including 365 days propelling time. (or) - CoC as MEO Class II + 24 Months Sea service including 485 days propelling time. , INDOS Number is Mandatory',
      ],
      CourseScheduleandFee: '22000',
      CoursePDF: '../ServerUpload/Courses/PDF/96.pdf',
      Code: 'MEO CLASS -1',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 20,
      CourseScheduleDetails: [],
    },
    {
      ID: 10,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'MEO CLASS II',
      Image: '../ServerUpload/Courses/ProfilePicture/10.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC',
        '\nCOC / COP ',
        '\nINDoS .\n&  BSID',
      ],
      DurationofCourse: ['04 Months'],
      Eligibilty: ['COC Of M.E.O  Class  IV & Sea Service Certificate'],
      CourseScheduleandFee: '21000',
      CoursePDF: '../ServerUpload/Courses/PDF/10.pdf',
      Code: 'MEO CLASS-2',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 40,
      CourseScheduleDetails: [
        {
          ID: 20246,
          CourseID: 10,
          CourseDate: '01/Sep/2024',
          CourseEndDate: '31/Dec/2024',
          CourseFee: '21000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20247,
          CourseID: 10,
          CourseDate: '01/Oct/2024',
          CourseEndDate: '31/Jan/2025',
          CourseFee: '21000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20248,
          CourseID: 10,
          CourseDate: '01/Nov/2024',
          CourseEndDate: '28/Feb/2025',
          CourseFee: '21000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
        {
          ID: 20257,
          CourseID: 10,
          CourseDate: '01/Dec/2024',
          CourseEndDate: '31/Mar/2025',
          CourseFee: '21000',
          SeatAvaiable: 40,
          Reserved: 0,
          isActive: true,
          isEarlyBirdDiscountEligible: false,
          isPreviousStudent: true,
          NormalFilledUp: 0,
          ReservedFilledUp: 0,
          Filled: 0,
          Pending: 0,
          Approved: 0,
          Cancelled: 0,
          ApplicationPercentage: 0,
          ApprovedPercentage: 0,
          Alert: false,
        },
      ],
    },
    {
      ID: 69,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'SHIP MANEUVERING SIMULATOR (SMS)',
      Image: '../ServerUpload/Courses/ProfilePicture/69.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC ',
        '\nINDOS ',
        '\nCOC AS 1ST MATE(FG) OR CHIEF OFFICER(FG)\n&  BSID',
      ],
      DurationofCourse: ['05 Days'],
      Eligibilty: [
        'COC WITH SEA SERVICE OF AT LEAST 18 MONTHS AS CERTIFIED WATCH KEEPING OFFICER',
      ],
      CourseScheduleandFee: '18000',
      CoursePDF: '../ServerUpload/Courses/PDF/69.pdf',
      Code: 'SMS',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: false,
      TotalSeats: 8,
      CourseScheduleDetails: [],
    },
    {
      ID: 9,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'SIMULATOR- LIQUID CARGO HANDLING-OIL-MGMT LEVEL (LCHS)',
      Image: '../ServerUpload/Courses/ProfilePicture/9.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC ',
        '\nINDoS ',
        '\nCOC / Watchkeeping / COP / Cookery Certificate ',
        '\nTASCO  Certificate\n&  BSID',
      ],
      DurationofCourse: ['5 Days'],
      Eligibilty: [
        'Details of Simulator Courses for Deck Department  For the Year 2016',
      ],
      CourseScheduleandFee: '15000',
      CoursePDF: '../ServerUpload/Courses/PDF/9.pdf',
      Code: 'LCHS',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 8,
      CourseScheduleDetails: [],
    },
    {
      ID: 97,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Diesel Engine Combustion Gas Monitor Simulator Course (MEO Class -1)',
      Image: '../ServerUpload/Courses/ProfilePicture/97.jpg',
      Intro: '-',
      AboutCourse: '-',
      DocumentsRequired: [
        'INDOS\nPassport\nCDC\nCDC sailing pages (MEO Class -1)\nCOC MEO Class II\n&  BSID',
      ],
      DurationofCourse: ['3 Days'],
      Eligibilty: ['Candidates eligible to appear for MEO Class I exams'],
      CourseScheduleandFee: '5000',
      CoursePDF: '../ServerUpload/Courses/PDF/97.pdf',
      Code: 'DECGS',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 10,
      CourseScheduleDetails: [],
    },
    {
      ID: 98,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Engine Room Simulator -Management (Class II Level)',
      Image: '../ServerUpload/Courses/ProfilePicture/98.jpg',
      Intro: '-',
      AboutCourse: '-',
      DocumentsRequired: [
        'INDOS\nPassport\nCDC\nCDC Sailing Pages (For MEO Class II)\nMEO Class IV COC\n&  BSID',
      ],
      DurationofCourse: ['5 Days'],
      Eligibilty: ['Candidates eligible to appear for MEO Class II exams'],
      CourseScheduleandFee: '5000',
      CoursePDF: '../ServerUpload/Courses/PDF/98.pdf',
      Code: 'ERS-M',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 10,
      CourseScheduleDetails: [],
    },
    {
      ID: 74,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'ENGINE ROOM SIMULATOR (OPT.LEVEL)',
      Image: '../ServerUpload/Courses/ProfilePicture/74.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC ',
        '\nCOC ',
        '\nINDOS ',
        '\nTWO PHOTOS (30 X 25MM)\n&  BSID',
      ],
      DurationofCourse: ['03 Days'],
      Eligibilty: ['CLASS IV MARINE ENGINEER WITH 6 MONTHS OF SEA SERVICE'],
      CourseScheduleandFee: '3500',
      CoursePDF: '../ServerUpload/Courses/PDF/74.pdf',
      Code: 'ERS',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: false,
      TotalSeats: 10,
      CourseScheduleDetails: [],
    },
    {
      ID: 99,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'HIGH VOLTAGE (Operation level)',
      Image: '../ServerUpload/Courses/ProfilePicture/99.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT,\nCDC,\nCOC,\nINDoS\n2 PHOTOGRAPHS (Passport size).\nEFA & PSSR\n&  BSID',
      ],
      DurationofCourse: ['1 days'],
      Eligibilty: ['6 MONTHS SEA SERVICE'],
      CourseScheduleandFee: '2800',
      CoursePDF: '../ServerUpload/Courses/PDF/99.pdf',
      Code: 'HV(OP)',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 10,
      CourseScheduleDetails: [],
    },
    {
      ID: 100,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'HIGH VOLTAGE (Management level)',
      Image: '../ServerUpload/Courses/ProfilePicture/100.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        '12 MONTHS SEA SERVICE AFTER MEO-IV\nPASSPORT,\nCDC,\nCOC,\nINDoS\n&  BSID',
      ],
      DurationofCourse: ['5 days'],
      Eligibilty: ['12 MONTHS SEA SERVICE'],
      CourseScheduleandFee: '10300',
      CoursePDF: '../ServerUpload/Courses/PDF/100.pdf',
      Code: 'HIGH VOLTAGE((M))',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 10,
      CourseScheduleDetails: [],
    },
    {
      ID: 127,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Automatic Radar Plotting Aids (ARPA)',
      Image: '../ServerUpload/Courses/ProfilePicture/127.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport\nCDC\nCDC sailing Pages                     \nROC / ROSC Certificate\n& BSID',
      ],
      DurationofCourse: ['5 Days'],
      Eligibilty: ['All Officers holding Radar Observer Course(ROC).'],
      CourseScheduleandFee: '4000',
      CoursePDF: '../ServerUpload/Courses/PDF/127.pdf',
      Code: 'ARPA',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 9,
      CourseScheduleDetails: [],
    },
    {
      ID: 123,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Electronic Chart Display and Information Systems (ECDIS)',
      Image: '../ServerUpload/Courses/ProfilePicture/123.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport\nCDC\nCOC\n INDOS\nROC / ROSC Certificate\n3 Months - Bridge watchkeeping certificate by Master (Master Sailing Exp Letter) - Minimum\nARPA  &  BSID',
      ],
      DurationofCourse: ['5 Days'],
      Eligibilty: [
        'Passport\nCDC\nCOC\nROC / ROSC Certificate\n3 Months - Bridge watchkeeping certificate by Master (Master Sailing Exp Letter) Minimum\nARPA',
      ],
      CourseScheduleandFee: '8000',
      CoursePDF: '../ServerUpload/Courses/PDF/123.pdf',
      Code: 'ECDIS',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: false,
      TotalSeats: 6,
      CourseScheduleDetails: [],
    },
    {
      ID: 124,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Radar Observer Simulator (ROSC)',
      Image: '../ServerUpload/Courses/ProfilePicture/124.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: ['Passport\nCDC\nCDC sailing Pages\n&  BSID'],
      DurationofCourse: ['10 Days'],
      Eligibilty: [
        'Navigating Officers (or) Pilots (or) Cadets : 3 Months Pre-sea training with 9 months Sea Service (or) Cadets with 18 months Sea Service (or) Others : 24 months Sea Service.',
      ],
      CourseScheduleandFee: '6000',
      CoursePDF: '../ServerUpload/Courses/PDF/124.pdf',
      Code: 'ROSC',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 9,
      CourseScheduleDetails: [],
    },
    {
      ID: 128,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Radar and Navigation Simulator (RANSCO)',
      Image: '../ServerUpload/Courses/ProfilePicture/128.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport,\nCDC,\nCOC (for Officers)\nROC / ROSC, ARPA Certificate\n& BSID',
      ],
      DurationofCourse: ['6 Days'],
      Eligibilty: ['Navigating officers with COC.'],
      CourseScheduleandFee: '7500',
      CoursePDF: '../ServerUpload/Courses/PDF/128.pdf',
      Code: 'RANSCO',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 6,
      CourseScheduleDetails: [],
    },
    {
      ID: 84,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Basic STCW Safety Course (PST, FPFF, PSSR, EFA Combined)',
      Image: '../ServerUpload/Courses/ProfilePicture/84.jpg',
      Intro: null,
      AboutCourse: 'PST, FPFF, PSSR, EFA Combined',
      DocumentsRequired: ['INDOS\nPassport (if available)'],
      DurationofCourse: [null],
      Eligibilty: [
        'INDOS Certification (Minimun 10th Grade pass, Indos application to DGS will be made by the Institute, only if the students enroll )\n**MEDICAL MASTER CHECKER PRINTOUT WITH VALID',
      ],
      CourseScheduleandFee: '12200',
      CoursePDF: '../ServerUpload/Courses/PDF/84.pdf',
      Code: 'BASIC STCW',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 20,
      CourseScheduleDetails: [],
    },
    {
      ID: 2,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Security Training for Seafarer with Designated Security duties (STSDSD)',
      Image: '../ServerUpload/Courses/ProfilePicture/2.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC No. ',
        '\nINDoS No. ',
        '\nCOC/COP/Watch Keeping/ Cookery Certificate',
      ],
      DurationofCourse: ['02 Days'],
      Eligibilty: [
        'ALL SEA FARERS OR PROSPECTIVE SEA FARERS ',
        ' \n10TH PASS CERTIFICATE/BIRTH CERTIFICATE/PASSPORT',
      ],
      CourseScheduleandFee: '2800',
      CoursePDF: '../ServerUpload/Courses/PDF/2.pdf',
      Code: 'STSDSD',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 88,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Basic Training for Oil and Chemical Tanker Cargo Operations (OCTO : OTF & CTF Combined)',
      Image: '../ServerUpload/Courses/ProfilePicture/88.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'INDOS\nFPFF Certificate (STCW 2010)\nEFA Certificate (STCW 2010)\nAug. FPFF / AFF Certificate (Only If available)\nCDC (if available)\nPassport (if available)\n&  BSID',
      ],
      DurationofCourse: ['6 Day(s)'],
      Eligibilty: [
        'INDOS Number, FPFF Certificate & EFA Certificate; NOTE: To book any course, you must atleast Pay the Booking Fee, the Balance fee (Total Course Fee - Booking Fee) must be paid on the 1st Day of the Course at the Reception in Cash or Card.\n**MEDICAL MASTER CHECKER PRINTOUT WITH VALID',
      ],
      CourseScheduleandFee: '4500',
      CoursePDF: '../ServerUpload/Courses/PDF/88.pdf',
      Code: 'OCTO',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 5,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'BASIC TRAINING FOR LIQUEFIED GAS TANKER CARGO OPERATIONS COURSE (LGTFC)',
      Image: '../ServerUpload/Courses/ProfilePicture/5.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC ',
        '\nINDoS ',
        '\nCOC / Watchkeeping / COP / Cookery Certificate\nMedical certficate\n&  BSID',
      ],
      DurationofCourse: ['5 Days'],
      Eligibilty: ["ADD'L DOC -\nFPFF, EFA, PST & PSSR CERTIFICATE"],
      CourseScheduleandFee: '5300',
      CoursePDF: '../ServerUpload/Courses/PDF/5.pdf',
      Code: 'GTFC',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 66,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'REFRESHER TRAINING FOR PROFICIENCY IN PERSONAL SURVIVAL TECHNIQUES (PST-REF)',
      Image: '../ServerUpload/Courses/ProfilePicture/66.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC ',
        '\nINDOS ',
        '\nPST CERTIFICATE ',
        '\nExtra one set of inner garments & towel for jumping into water ',
        '\nBoiler suit & safety shoes\n&  BSID',
      ],
      DurationofCourse: ['01 Day'],
      Eligibilty: [
        'MEDICAL FITNESS CERTIFICATE FROM REGISTER MEDICAL PRACTITIONER (NOT MORE THAN ONE MONTH FROM COMMENCEMENT DATE OF COURSE)\n**MEDICAL MASTER CHECKER \nPRINTOUT WITH VALID',
      ],
      CourseScheduleandFee: '2000',
      CoursePDF: '../ServerUpload/Courses/PDF/66.pdf',
      Code: 'PST-REF',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 67,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'REFRESHER TRAINING FOR PROFICIENCY IN FIRE PREVENTION & FIRE FIGHTING(FPFF-REF)',
      Image: '../ServerUpload/Courses/ProfilePicture/67.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC ',
        '\nINDOS ',
        '\nFPFF CERTIFICATE\n&  BSID',
      ],
      DurationofCourse: ['01 Day'],
      Eligibilty: [
        'REGISTER MEDICAL PRACTITIONER (NOT MORE THAN ONE MONTH FROM COMMENCEMENT DATE OF PST/FPFF)\n**MEDICAL MASTER CHECKER PRINTOUT WITH VALID',
      ],
      CourseScheduleandFee: '2000',
      CoursePDF: '../ServerUpload/Courses/PDF/67.pdf',
      Code: 'FPFF-REF',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 82,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'REFRESHER TRAINING FOR PROFICIENCY IN PSCRB  ( PSCRB  REF)',
      Image: '../ServerUpload/Courses/ProfilePicture/82.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC ',
        '\nINDoS ',
        '\nPSCRB Certificate ',
        '\nDG Approved Medical Fitness ',
        '\nExtra one set of inner garments& towel for jumping into water ',
        '\nBoiler suit & safety shoes\n&  BSID',
      ],
      DurationofCourse: ['1 Day'],
      Eligibilty: [
        '6 Months Seatime\n**MEDICAL MASTER CHECKER PRINTOUT WITH VALID',
      ],
      CourseScheduleandFee: '4400',
      CoursePDF: '../ServerUpload/Courses/PDF/82.pdf',
      Code: 'PSCRB-REF',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 78,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'REFRESHER TRAINING FOR ADVANCED FIRE FIGHTING (AFF REF)',
      Image: '../ServerUpload/Courses/ProfilePicture/78.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'INDOS ',
        '\nCDC ',
        '\nPASSPORT ',
        '\nAFF CERTIFICATE ',
        '\nDG APPROVED VALID MEDICAL FITNESS CERTIFICATE ',
        '\nCOLOR PHOTOGRAPH 2 COPIES ',
        '\nBOILER SUIT & SAFETY SHOES\n&  BSID',
      ],
      DurationofCourse: ['01 Day'],
      Eligibilty: [
        'MEDICAL FITNESS CERTIFICATE FROM REGISTER MEDICAL PRACTITIONER , SEA TIME ATLEAST 6 MONTHS\n**MEDICAL MASTER CHECKER PRINTOUT WITH VALID',
      ],
      CourseScheduleandFee: '4400',
      CoursePDF: '../ServerUpload/Courses/PDF/78.pdf',
      Code: 'AFF-REF',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 79,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'Medical care Refresher (MC-REF)',
      Image: '../ServerUpload/Courses/ProfilePicture/79.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'Passport ',
        '\nCDC ',
        '\nINDoS ',
        '\nCOC As 2nd Mate (FG) ',
        '\nMedicare Certificate\n&  BSID',
      ],
      DurationofCourse: ['1 Day'],
      Eligibilty: ['COC As 2nd Mate (FG)'],
      CourseScheduleandFee: '3800',
      CoursePDF: '../ServerUpload/Courses/PDF/79.pdf',
      Code: 'MEDREF',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: false,
      TotalSeats: 20,
      CourseScheduleDetails: [],
    },
    {
      ID: 81,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'MEDICAL FIRST AID REFRESHER (MFA-REF)',
      Image: '../ServerUpload/Courses/ProfilePicture/81.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'PASSPORT ',
        '\nCDC  ',
        '\nCOC/COP  ',
        '\nINDOS\n&  BSID',
      ],
      DurationofCourse: ['01 Day'],
      Eligibilty: [
        'AN APPROVED SEA GOING SERVICES FOR SIX MONTHS ',
        '\nCOPY OF MFA CERTIFICATE',
      ],
      CourseScheduleandFee: '2300',
      CoursePDF: '../ServerUpload/Courses/PDF/81.pdf',
      Code: 'MFA (REFRESHER)',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
    {
      ID: 50,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'PERSONAL SAFETY & SOCIAL RESPONSIBILITIES',
      Image: '../ServerUpload/Courses/ProfilePicture/50.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'ALL SEA FARERS OR PROSPECTIVE SEA FARERS ',
        '\n10TH PASS CERTIFICATE/BIRTH CERTIFICATE/PASSPORT ',
        '\nINDOS\n&  BSID',
      ],
      DurationofCourse: ['04 Days'],
      Eligibilty: ['CDC'],
      CourseScheduleandFee: '9300',
      CoursePDF: '../ServerUpload/Courses/PDF/50.pdf',
      Code: 'PSSR',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: false,
      TotalSeats: 15,
      CourseScheduleDetails: [],
    },
    {
      ID: 101,
      CourseInstituteID: 0,
      CourseTypeID: 0,
      Name: 'ELEMENTARY FIRST AID',
      Image: '../ServerUpload/Courses/ProfilePicture/101.jpg',
      Intro: null,
      AboutCourse: null,
      DocumentsRequired: [
        'All seafarers or prospective seafarers.\nSchool Pass Certificate -10th',
      ],
      DurationofCourse: ['3 Days'],
      Eligibilty: ['CDC'],
      CourseScheduleandFee: '5300',
      CoursePDF: '../ServerUpload/Courses/PDF/101.pdf',
      Code: 'EFA',
      isActive: true,
      isEarlyBirdDiscountEligible: false,
      isPreviousStudent: true,
      TotalSeats: 24,
      CourseScheduleDetails: [],
    },
  ]
  